apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: konga-database
  name: konga-database
  namespace: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: konga-database
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: konga-database
    spec:
      containers:
        - image: mongo:4.1.5
          imagePullPolicy: ""
          name: konga-database
          ports:
            - containerPort: 27017
          resources: {}
          volumeMounts:
            - mountPath: /data/db
              name: konga-data
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
        - name: konga-data
          persistentVolumeClaim:
            claimName: konga-data
status: {}
