apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: kong
  name: kong
  labels:
    app: kong
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  namespace: kong
  name: kong
  labels:
    app: kong
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: kong
  name: kong-control-plane-bootstrap
  labels:
    app: kong-control-plane-bootstrap
spec:
  template:
    metadata:
      name: kong-control-plane-bootstrap
      labels:
        app: kong-control-plane
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: KONG_PG_PORT
              value: "5432"
            - name: KONG_PG_HOST
              value: postgres.kong.svc
          command:
            [
              "/bin/sh",
              "-c",
              "until nc -zv $KONG_PG_HOST $KONG_PG_PORT -w1; do echo 'waiting for db'; sleep 1; done",
            ]
      containers:
        - name: kong-migration-boostrap
          image: kong
          imagePullPolicy: IfNotPresent
          env:
            - name: KONG_PG_PASSWORD
              value: kong
            - name: KONG_PG_HOST
              value: postgres.kong.svc
            - name: KONG_NGINX_WORKER_PROCESSES
              value: "1"
          command: ["kong", "migrations", "bootstrap"]
      restartPolicy: OnFailure
