apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: kong
    app: kong
  name: kong
  namespace: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kong
      app: kong
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: kong
        app: kong
    spec:
      containers:
        - env:
            - name: KONG_ADMIN_ACCESS_LOG
              value: /dev/stdout
            - name: KONG_ADMIN_ERROR_LOG
              value: /dev/stderr
            - name: KONG_ADMIN_LISTEN
              value: 0.0.0.0:8001
            - name: KONG_DATABASE
              value: postgres
            - name: KONG_PG_HOST
              value: postgres.kong.svc
            - name: KONG_PG_PASSWORD
              value: kong
            - name: KONG_PROXY_ACCESS_LOG
              value: /dev/stdout
            - name: KONG_PROXY_ERROR_LOG
              value: /dev/stderr
            - name: ROLLING
              value: "0"
          image: kong:latest
          imagePullPolicy: ""
          name: kong
          ports:
            - containerPort: 8000
            - containerPort: 8001
            - containerPort: 8443
          resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
