apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: client
  name: client
spec:
  type: LoadBalancer
  ports:
  - name: "label-generator"
    port: 80
    targetPort: 3000
  selector:
    io.kompose.service: client
status:
  loadBalancer: {}
