export const API_URL = 'http://localhost:1780/';


export const COLOR_LIST = {
    "en": [
        { name: 'Black' },
        { name: 'White' },
        { name: 'Gray' },
        { name: 'Beige' },
        { name: 'Nude' },
        { name: 'Red' },
        { name: 'Green' },
        { name: 'Blue' },
        { name: 'Navy' },
        { name: 'Light Blue' },
        { name: 'Yellow' },
        { name: 'Purple' },
        { name: 'Pink' },
        { name: 'Orange' },
        { name: 'Brown' },
        { name: 'Off White' },
        { name: 'Cream' },
        { name: 'Khaki' },
        { name: 'Jeans' },
        { name: 'Gold' },
        { name: 'Silver' },
        { name: 'Dark Red' },
        { name: 'Colorful' },
        { name: 'Other' }
    ],
    "th": [
        { name:'สีดำ' },
        { name:'สีขาว' },
        { name:'สีเทา' },
        { name:'สีเบจ' },
        { name:'สีนู้ด' },
        { name:'สีแดง' },
        { name:'สีเขียว' },
        { name:'สีน้ำเงิน' },
        { name:'สีกรมท่า' },
        { name:'สีฟ้า' },
        { name:'สีเหลือง' },
        { name:'สีม่วง' },
        { name:'สีชมพู' },
        { name:'สีส้ม' },
        { name:'สีน้ำตาล' },
        { name:'สีออฟไวท์' },
        { name:'สีครีม' },
        { name:'สีกากี' },
        { name:'สียีนส์' },
        { name:'สีทอง' },
        { name:'สีเงิน' },
        { name:'สีเลือดหมู' },
        { name:'หลากสี' },
        { name:'อื่นๆ' }
    ]
};

export const PRODUCT_CATEGORY_LIST = {
    "en": [
        { name: "Men's Fashion", level: "Category", parent: [] },
        { name: "Women's Fashion", level: "Category", parent: [] },

        { name: "T-Shirt", level: "Sub Category 1", parent: [{name: "Men's Fashion"}] },
        { name: "Shirt", level: "Sub Category 1", parent: [{name: "Men's Fashion"}] },
        { name: "Polo Shirt", level: "Sub Category 1", parent: [{name: "Men's Fashion"}] },
        { name: "Coat", level: "Sub Category 1", parent: [{name: "Men's Fashion"}] },
        { name: "Shorts", level: "Sub Category 1", parent: [{name: "Men's Fashion"}] },
        { name: "Trousers", level: "Sub Category 1", parent: [{name: "Men's Fashion"}] },
        { name: "Jeans", level: "Sub Category 1", parent: [{name: "Men's Fashion"}] },
        { name: "Underwear", level: "Sub Category 1", parent: [{name: "Men's Fashion"}] },
        { name: "Long John", level: "Sub Category 1", parent: [{name: "Men's Fashion"}] },
        { name: "Glove", level: "Sub Category 1", parent: [{name: "Men's Fashion"}] },

        { name: "Tops", level: "Sub Category 1", parent: [{name: "Women's Fashion"}] },
        { name: "Dress", level: "Sub Category 1", parent: [{name: "Women's Fashion"}] },
        { name: "Skirt", level: "Sub Category 1", parent: [{name: "Women's Fashion"}] },
        { name: "Pants", level: "Sub Category 1", parent: [{name: "Women's Fashion"}] },
        { name: "Jacket and Coat", level: "Sub Category 1", parent: [{name: "Women's Fashion"}] },
        { name: "Jumpsuits", level: "Sub Category 1", parent: [{name: "Women's Fashion"}] },
        { name: "Underwear", level: "Sub Category 1", parent: [{name: "Women's Fashion"}] },
        { name: "Pajamas", level: "Sub Category 1", parent: [{name: "Women's Fashion"}] },
        { name: "Nightgown", level: "Sub Category 1", parent: [{name: "Women's Fashion"}] },

        { name: "Plain Color", level: "Sub Category 2", parent: [{name: "T-Shirt"}, {name: "Shirt"}, {name: "Polo Shirt"}] },
        { name: "Pattern Screen", level: "Sub Category 2", parent: [{name: "T-Shirt"}, {name: "Shirt"}, {name: "Polo Shirt"}] },
        { name: "Striped Screen", level: "Sub Category 2", parent: [{name: "T-Shirt"}, {name: "Shirt"}, {name: "Polo Shirt"}] },
        { name: "Alphabet Screen", level: "Sub Category 2", parent: [{name: "T-Shirt"}] },
        { name: "Graphic Screen", level: "Sub Category 2", parent: [{name: "T-Shirt"}] },
        { name: "Sleeveless", level: "Sub Category 2", parent: [{name: "T-Shirt"}] },
        { name: "Sweater and Cardigan", level: "Sub Category 2", parent: [{name: "Coat"}] },
        { name: "Jacket and Coat", level: "Sub Category 2", parent: [{name: "Coat"}] },
        { name: "Hoodie", level: "Sub Category 2", parent: [{name: "Coat"}] },
        { name: "Suit", level: "Sub Category 2", parent: [{name: "Coat"}] },
        { name: "Denim Jacket", level: "Sub Category 2", parent: [{name: "Coat"}] },
        { name: "Elastic Waist Shorts", level: "Sub Category 2", parent: [{name: "Shorts"}] },
        { name: "Fabric Shorts", level: "Sub Category 2", parent: [{name: "Shorts"}] },
        { name: "Shorts", level: "Sub Category 2", parent: [{name: "Shorts"}, {name: "Jeans"}] },
        { name: "Straight Leg", level: "Sub Category 2", parent: [{name: "Trousers"}, {name: "Jeans"}] },
        { name: "Skinny Leg", level: "Sub Category 2", parent: [{name: "Trousers"}, {name: "Jeans"}] },
        { name: "Jogger", level: "Sub Category 2", parent: [{name: "Trousers"}] },
        { name: "Vest", level: "Sub Category 2", parent: [{name: "Underwear"}] },
        { name: "Briefs", level: "Sub Category 2", parent: [{name: "Underwear"}] },
        { name: "Boxer", level: "Sub Category 2", parent: [{name: "Underwear"}] },

        { name: "Sets", level: "Sub Category 2", parent: [{name: "Tops"}] },
        { name: "T-Shirt", level: "Sub Category 2", parent: [{name: "Tops"}] },
        { name: "Shoulder Shirts", level: "Sub Category 2", parent: [{name: "Tops"}] },
        { name: "Crop Top", level: "Sub Category 2", parent: [{name: "Tops"}] },
        { name: "Oversize", level: "Sub Category 2", parent: [{name: "Tops"}] },
        { name: "Strapless", level: "Sub Category 2", parent: [{name: "Tops"}] },
        { name: "Vest/Spaghetti Strap", level: "Sub Category 2", parent: [{name: "Tops"}] },
        { name: "Shirt", level: "Sub Category 2", parent: [{name: "Tops"}] },
        { name: "Polo Shirt", level: "Sub Category 2", parent: [{name: "Tops"}] },
        { name: "Short Dress", level: "Sub Category 2", parent: [{name: "Dress"}] },
        { name: "Long Dress", level: "Sub Category 2", parent: [{name: "Dress"}] },
        { name: "Mini Skirt", level: "Sub Category 2", parent: [{name: "Skirt"}] },
        { name: "Maxi Skirt", level: "Sub Category 2", parent: [{name: "Skirt"}] },
        { name: "Denim Skirt", level: "Sub Category 2", parent: [{name: "Skirt"}] },
        { name: "Divided Skirt", level: "Sub Category 2", parent: [{name: "Skirt"}] },
        { name: "Shorts", level: "Sub Category 2", parent: [{name: "Pants"}] },
        { name: "Trousers", level: "Sub Category 2", parent: [{name: "Pants"}] },
        { name: "Legging", level: "Sub Category 2", parent: [{name: "Pants"}] },
        { name: "Jeans", level: "Sub Category 2", parent: [{name: "Pants"}] },
        { name: "Cardigan", level: "Sub Category 2", parent: [{name: "Jacket and Coat"}] },
        { name: "Sweater", level: "Sub Category 2", parent: [{name: "Jacket and Coat"}] },
        { name: "Jacket", level: "Sub Category 2", parent: [{name: "Jacket and Coat"}] },
        { name: "Sweater Vest", level: "Sub Category 2", parent: [{name: "Jacket and Coat"}] },
        { name: "Coat", level: "Sub Category 2", parent: [{name: "Jacket and Coat"}] },
        { name: "Hoodie", level: "Sub Category 2", parent: [{name: "Jacket and Coat"}] },
        { name: "Suit", level: "Sub Category 2", parent: [{name: "Jacket and Coat"}] },
        { name: "Short Jumpsuit", level: "Sub Category 2", parent: [{name: "Jumpsuits"}] },
        { name: "Long Jumpsuit", level: "Sub Category 2", parent: [{name: "Jumpsuits"}] },
        { name: "Jumper", level: "Sub Category 2", parent: [{name: "Jumpsuits"}] },
        { name: "Brassiere", level: "Sub Category 2", parent: [{name: "Underwear"}] },
        { name: "Panties", level: "Sub Category 2", parent: [{name: "Underwear"}] },
        { name: "Shapewear", level: "Sub Category 2", parent: [{name: "Underwear"}] },
        { name: "Lingerie", level: "Sub Category 2", parent: [{name: "Underwear"}] },
        { name: "Outfit", level: "Sub Category 2", parent: [{name: "Pajamas"}] },
        { name: "Shirt", level: "Sub Category 2", parent: [{name: "Nightgown"}] },
        { name: "Pants", level: "Sub Category 2", parent: [{name: "Nightgown"}] },
        { name: "Dress", level: "Sub Category 2", parent: [{name: "Nightgown"}] },
        { name: "Sexy", level: "Sub Category 2", parent: [{name: "Nightgown"}] },
    ],
    "th": [
        { name: "เสื้อผ้าแฟชั่นผู้ชาย", level: "Category", parent: [] },
        { name: "เสื้อผ้าแฟชั่นผู้หญิง", level: "Category", parent: [] },

        { name: "เสื้อยืด", level: "Sub Category 1", parent: [{name: "เสื้อผ้าแฟชั่นผู้ชาย"}] },
        { name: "เสื้อเชิ้ต", level: "Sub Category 1", parent: [{name: "เสื้อผ้าแฟชั่นผู้ชาย"}] },
        { name: "เสื้อโปโล", level: "Sub Category 1", parent: [{name: "เสื้อผ้าแฟชั่นผู้ชาย"}] },
        { name: "เสื้อคลุมตัวนอก", level: "Sub Category 1", parent: [{name: "เสื้อผ้าแฟชั่นผู้ชาย"}] },
        { name: "กางเกงขาสั้น", level: "Sub Category 1", parent: [{name: "เสื้อผ้าแฟชั่นผู้ชาย"}] },
        { name: "กางเกงขายาว", level: "Sub Category 1", parent: [{name: "เสื้อผ้าแฟชั่นผู้ชาย"}] },
        { name: "กางเกงยีนส์", level: "Sub Category 1", parent: [{name: "เสื้อผ้าแฟชั่นผู้ชาย"}] },
        { name: "ชุดชั้นในชาย", level: "Sub Category 1", parent: [{name: "เสื้อผ้าแฟชั่นผู้ชาย"}] },
        { name: "ลองจอน", level: "Sub Category 1", parent: [{name: "เสื้อผ้าแฟชั่นผู้ชาย"}] },
        { name: "ถุงมือ", level: "Sub Category 1", parent: [{name: "เสื้อผ้าแฟชั่นผู้ชาย"}] },

        { name: "เสื้อ", level: "Sub Category 1", parent: [{name: "เสื้อผ้าแฟชั่นผู้หญิง"}] },
        { name: "เดรส", level: "Sub Category 1", parent: [{name: "เสื้อผ้าแฟชั่นผู้หญิง"}] },
        { name: "กระโปรง", level: "Sub Category 1", parent: [{name: "เสื้อผ้าแฟชั่นผู้หญิง"}] },
        { name: "กางเกง", level: "Sub Category 1", parent: [{name: "เสื้อผ้าแฟชั่นผู้หญิง"}] },
        { name: "แจ็คเก็ตและโค้ด", level: "Sub Category 1", parent: [{name: "เสื้อผ้าแฟชั่นผู้หญิง"}] },
        { name: "จั๊มสูท", level: "Sub Category 1", parent: [{name: "เสื้อผ้าแฟชั่นผู้หญิง"}] },
        { name: "ชุดชั้นในผู้หญิง", level: "Sub Category 1", parent: [{name: "เสื้อผ้าแฟชั่นผู้หญิง"}] },
        { name: "ชุดนอน", level: "Sub Category 1", parent: [{name: "เสื้อผ้าแฟชั่นผู้หญิง"}] },
        { name: "ชุดนอน", level: "Sub Category 1", parent: [{name: "เสื้อผ้าแฟชั่นผู้หญิง"}] },

        { name: "สีพื้น", level: "Sub Category 2", parent: [{name: "เสื้อยืด"}, {name: "เสื้อเชิ้ต"}, {name: "เสื้อโปโล"}] },
        { name: "มีลาย", level: "Sub Category 2", parent: [{name: "เสื้อยืด"}, {name: "เสื้อเชิ้ต"}, {name: "เสื้อโปโล"}] },
        { name: "ลายทาง", level: "Sub Category 2", parent: [{name: "เสื้อยืด"}, {name: "เสื้อเชิ้ต"}, {name: "เสื้อโปโล"}] },
        { name: "สกรีนตัวหนังสือ", level: "Sub Category 2", parent: [{name: "เสื้อยืด"}] },
        { name: "ลายการ์ตูน", level: "Sub Category 2", parent: [{name: "เสื้อยืด"}] },
        { name: "เสื้อแขนกุด", level: "Sub Category 2", parent: [{name: "เสื้อยืด"}] },
        { name: "สเว็ตเตอร์และคาร์ดิแกน", level: "Sub Category 2", parent: [{name: "เสื้อคลุมตัวนอก"}] },
        { name: "แจ็คเก็ตและโค้ด", level: "Sub Category 2", parent: [{name: "เสื้อคลุมตัวนอก"}] },
        { name: "เสื้อฮู้ด", level: "Sub Category 2", parent: [{name: "เสื้อคลุมตัวนอก"}] },
        { name: "เสื้อสูท", level: "Sub Category 2", parent: [{name: "เสื้อคลุมตัวนอก"}] },
        { name: "แจ็คเก็ตยีนส์", level: "Sub Category 2", parent: [{name: "เสื้อคลุมตัวนอก"}] },
        { name: "กางเกงขาสั้นเอวยางยืด", level: "Sub Category 2", parent: [{name: "กางเกงขาสั้น"}] },
        { name: "กางเกงขาสั้นผ้า", level: "Sub Category 2", parent: [{name: "กางเกงขาสั้น"}] },
        { name: "กางเกงขาสั้น", level: "Sub Category 2", parent: [{name: "กางเกงขาสั้น"}, {name: "กางเกงยีนส์"}] },
        { name: "ขากระบอก", level: "Sub Category 2", parent: [{name: "กางเกงขายาว"}, {name: "กางเกงยีนส์"}] },
        { name: "ขาเดฟ", level: "Sub Category 2", parent: [{name: "กางเกงขายาว"}, {name: "กางเกงยีนส์"}] },
        { name: "กางเกงจ็อกเกอร์", level: "Sub Category 2", parent: [{name: "กางเกงขายาว"}] },
        { name: "เสื้อกล้าม", level: "Sub Category 2", parent: [{name: "ชุดชั้นในชาย"}] },
        { name: "กางเกงใน", level: "Sub Category 2", parent: [{name: "ชุดชั้นในชาย"}] },
        { name: "บ็อกเซอร์", level: "Sub Category 2", parent: [{name: "ชุดชั้นในชาย"}] },

        { name: "ชุดเข้าเซ็ท", level: "Sub Category 2", parent: [{name: "เสื้อ"}] },
        { name: "เสื้อยืด", level: "Sub Category 2", parent: [{name: "เสื้อ"}] },
        { name: "เสื้อปาดไหล่", level: "Sub Category 2", parent: [{name: "เสื้อ"}] },
        { name: "เสื้อครอป ท็อป", level: "Sub Category 2", parent: [{name: "เสื้อ"}] },
        { name: "เสื้อทรงใหญ่", level: "Sub Category 2", parent: [{name: "เสื้อ"}] },
        { name: "เกาะอก", level: "Sub Category 2", parent: [{name: "เสื้อ"}] },
        { name: "เสื้อกล้าม/สายเดี่ยว", level: "Sub Category 2", parent: [{name: "เสื้อ"}] },
        { name: "เสื้อเชิ้ต", level: "Sub Category 2", parent: [{name: "เสื้อ"}] },
        { name: "เสื้อโปโล", level: "Sub Category 2", parent: [{name: "เสื้อ"}] },
        { name: "เดรสสั้น", level: "Sub Category 2", parent: [{name: "เดรส"}] },
        { name: "เดรสยาว", level: "Sub Category 2", parent: [{name: "เดรส"}] },
        { name: "กระโปรงสั้น", level: "Sub Category 2", parent: [{name: "กระโปรง"}] },
        { name: "กระโปรงยาว", level: "Sub Category 2", parent: [{name: "กระโปรง"}] },
        { name: "กระโปรงยีนส์", level: "Sub Category 2", parent: [{name: "กระโปรง"}] },
        { name: "กระโปรงกางเกง", level: "Sub Category 2", parent: [{name: "กระโปรง"}] },
        { name: "กางเกงขาสั้น", level: "Sub Category 2", parent: [{name: "กางเกง"}] },
        { name: "กางเกงขายาว", level: "Sub Category 2", parent: [{name: "กางเกง"}] },
        { name: "เลกกิ้ง", level: "Sub Category 2", parent: [{name: "กางเกง"}] },
        { name: "กางเกงยีนส์", level: "Sub Category 2", parent: [{name: "กางเกง"}] },
        { name: "เสื้อคาร์ดิแกน", level: "Sub Category 2", parent: [{name: "แจ็คเก็ตและโค้ด"}] },
        { name: "เสื้อสเวตเตอร์", level: "Sub Category 2", parent: [{name: "แจ็คเก็ตและโค้ด"}] },
        { name: "เสื้อแจ็คเก็ต", level: "Sub Category 2", parent: [{name: "แจ็คเก็ตและโค้ด"}] },
        { name: "เสื้อกั๊ก", level: "Sub Category 2", parent: [{name: "แจ็คเก็ตและโค้ด"}] },
        { name: "เสื้อโค้ด", level: "Sub Category 2", parent: [{name: "แจ็คเก็ตและโค้ด"}] },
        { name: "เสื้อฮู้ด", level: "Sub Category 2", parent: [{name: "แจ็คเก็ตและโค้ด"}] },
        { name: "เสื้อสูท", level: "Sub Category 2", parent: [{name: "แจ็คเก็ตและโค้ด"}] },
        { name: "จั๊มสูทขาสั้น", level: "Sub Category 2", parent: [{name: "จั๊มสูท"}] },
        { name: "จั๊มสูทขายาว", level: "Sub Category 2", parent: [{name: "จั๊มสูท"}] },
        { name: "เอี๊ยม", level: "Sub Category 2", parent: [{name: "จั๊มสูท"}] },
        { name: "เสื้อชั้นใน", level: "Sub Category 2", parent: [{name: "ชุดชั้นในผู้หญิง"}] },
        { name: "กางเกงชั้นใน", level: "Sub Category 2", parent: [{name: "ชุดชั้นในผู้หญิง"}] },
        { name: "ชุดกระชับสัดส่วน", level: "Sub Category 2", parent: [{name: "ชุดชั้นในผู้หญิง"}] },
        { name: "เสื้อและกางเกงซับใน", level: "Sub Category 2", parent: [{name: "ชุดชั้นในผู้หญิง"}] },
        { name: "ทั้งชุด", level: "Sub Category 2", parent: [{name: "ชุดนอน"}] },
        { name: "เสื้อนอน", level: "Sub Category 2", parent: [{name: "ชุดนอน"}] },
        { name: "กางเกงนอน", level: "Sub Category 2", parent: [{name: "ชุดนอน"}] },
        { name: "ชุดนอนเดรส", level: "Sub Category 2", parent: [{name: "ชุดนอน"}] },
        { name: "ชุดนอนเซ็กซี่", level: "Sub Category 2", parent: [{name: "ชุดนอน"}] },
    ]
};

export const PRODUCT_ATTRIBUTE_LIST = [
    { id: 1, name: 'Cleaning Method', type: 'select', option: [ {lable: '', value: ''},  ]  },
];

