apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: api
  namespace: production
spec:
  minReplicas: 3
  maxReplicas: 15
  targetCPUUtilizationPercentage: 80
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: media
  namespace: production
spec:
  minReplicas: 1
  maxReplicas: 15
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 80
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: media
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: platform
  namespace: production
spec:
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: platform
