apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: alpha
  labels:
    io.kompose.service: redis-claim1
  name: redis-claim1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
